const styles = StyleSheet.create({
  container: {
    flex:  1,
    backgroundColor: '#0f172a',
  },
  centerContainer: {
    flex: 1,
    justifyContent:  'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#0f172a',
  },
  content: {
    padding: 20,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#94a3b8',
  },
  errorText: {
    fontSize: 18,
    color: '#ef4444',
    textAlign:  'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#f59e0b',
    paddingHorizontal: 30,
    paddingVertical:  12,
    borderRadius: 10,
  },
  retryButtonText:  {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  tripInfo: {
    backgroundColor: '#1e293b',
    padding: 20,
    borderRadius: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity:  0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  tripTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom:  15,
    color: '#ffffff',
  },
  locationRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  locationLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#94a3b8',
    width: 60,
  },
  locationText: {
    flex: 1,
    fontSize: 14,
    color:  '#cbd5e1',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#ffffff',
  },
  quoteCard: {
    backgroundColor: '#1e293b',
    padding:  20,
    borderRadius:  15,
    marginBottom:  15,
    borderWidth: 2,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity:  0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  bestQuoteCard: {
    borderColor: '#10b981',
    backgroundColor: '#1e293b',
    shadowColor: '#10b981',
  },
  bestBadge: {
    backgroundColor: '#10b981',
    paddingHorizontal: 12,
    paddingVertical:  6,
    borderRadius:  20,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  bestBadgeText: {
    color: '#fff',
    fontSize:  12,
    fontWeight:  'bold',
  },
  quoteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom:  15,
  },
  providerName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  price: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#f59e0b',
  },
  bestPrice: {
    color: '#10b981',
  },
  quoteDetails: {
    marginBottom: 10,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 14,
    color: '#94a3b8',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#cbd5e1',
  },
  savingsText: {
    marginTop: 10,
    fontSize: 14,
    color: '#10b981',
    fontWeight: '600',
    textAlign: 'center',
  },
  newSearchButton: {
    backgroundColor: '#f59e0b',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    shadowColor: '#f59e0b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  newSearchButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  securityNote: {
    backgroundColor: '#1e293b',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3b82f6',
  },
  securityText: {
    fontSize: 12,
    color:  '#3b82f6',
    textAlign: 'center',
  },
});